- name: Gather OS specific variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version }}.yml"
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version }}.yml"

- name: Gather DB specific variables
  when: kea_dhcp4_lease_database_type != "memfile"
  ansible.builtin.include_vars: "{{ kea_dhcp4_lease_database_type }}.yml"
